name: environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pyvista>=0.34.2
  - qt
  - pyqt
  - pydata-sphinx-theme
  - numpydoc
  - ipython
  - cython
  - pytest
  - pillow>=8.3.2
  - gcc>=12.1.0
variables:
  OMP_NUM_THREADS: 1
  PYTEST_QT_API: pyqt5
