{% set name = "rmc-discord" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rmc-discord-{{ version }}.tar.gz
  sha256: 4b8f18399c9383814b56760a8f6387b5ba4545f63de6c3b350bba6ea5db01919

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - cython
    - ipython
    - matplotlib-base
    - nexusformat
    - pycifrw
    - pyqt
    - python
    - pyvista
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - rmc_discord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zjmorgan/rmc-discord
  summary: Reverse Monte Carlo refinement of diffuse scattering and correlated disorder from single crystals
  license: GPL-3.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - zjmorgan
