name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        # to supply options, put them in 'env', like:
        env:
           CIBW_ARCHS: auto64
           CIBW_SKIP: pp* cp310-* *musllinux*
           CIBW_BEFORE_BUILD: pip install numpy cython
           CIBW_BEFORE_ALL_MACOS: brew install llvm libomp
           CIBW_ENVIRONMENT: "QT_QPA_PLATFORM=offscreen"
           CIBW_TEST_REQUIRES: pytest ipython cython
           CIBW_TEST_COMMAND: python -m pytest --pyargs disorder
           CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
           CIBW_MANYLINUX_I686_IMAGE: manylinux2014
           CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
           CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux2014
        with:
           package-dir: .
           output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
