name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
           CIBW_ARCHS: auto64
           CIBW_SKIP: pp*
           CIBW_BEFORE_ALL_MACOS: brew install libomp
           CIBW_TEST_REQUIRES: pytest
           CIBW_TEST_COMMAND: python -m pytest --pyargs disorder
           CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
           CIBW_MANYLINUX_I686_IMAGE: manylinux2014
           CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
           CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux2014

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
